version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - apt-get install build-essential checkinstall
      - apt-get install libssl-dev
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
      - npm ci
      - npm install 6.10.3
      - npm install serverless -g
  build:
    commands:
      - echo Building project...
      - echo Build started on `date`      
      #- serverless deploy
      - npm --version
  post_build:
    commands:
          - echo Build completed on `date`