version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm ci
      - npm install
      - npm install serverless -g
  build:
    commands:
      - echo Building project...
      - echo Build started on `date`      
      - serverless deploy
  post_build:
    commands:
          - echo Build completed on `date`